Konstantin_Belousov_JavaRush_Project_1
neighborstan/caesar-cipher pull request #1
Opened 2022-03-15 15:58 UTC by neighborstan

2022-03-15 21:26 UTC, Enotik-code reviewed
Отличная работа! Ждем 4-го шага))

2022-03-15 21:26 UTC, Enotik-code commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +    }
кажется методы одинаковые, можно использовать один

2022-03-15 21:26 UTC, Enotik-code commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +            if (action.equals(ENCRYPT)) {
в таких случаях, рекомендуется использовать ENCRYPT.equals(action)
потому что в action может придти null

2022-03-15 21:26 UTC, Enotik-code commented on src/com/javarush/caesarcipher/cipher/CaesarCipher.java
> +        String decryptedText = Files.readString(pathToDecryptedFile);
readString может выбросить IOException. Можешь создать свой класс для обработки работы с файлом.
Эта самая низкоуровневая операция и лучше обработать ошибку здесь, а не передавать пользователю

2022-03-15 21:26 UTC, Enotik-code commented on src/com/javarush/caesarcipher/cipher/CaesarCipher.java
> +        Files.writeString(pathToEncryptedFile, builderResultText.toString());
writeString может выбросить IOException. Можешь создать свой класс для обработки работы с файлом.
Эта самая низкоуровневая операция и лучше обработать ошибку здесь, а не передавать пользователю

2022-03-15 21:26 UTC, Enotik-code commented on src/com/javarush/caesarcipher/cipher/CaesarCipher.java
> +                    }
одна и та же операция, подумай, можно ли все время передавать symbol

2022-03-15 21:26 UTC, Enotik-code commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +                };
мы когда говорили об исключениях. разбирали места и примеры работы с пользователем, где хорошо бы использовать excpetion* кажется операция неверного ввода это не исключение, а простая не внимательность, лучше исправить на просто перезаписать значение и спросить новое

2022-03-15 21:26 UTC, Enotik-code commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +                if (key < 1 || key >= alphabetSize) throw new NumberFormatException();
см ниже

2022-03-15 21:26 UTC, Enotik-code commented on src/com/javarush/caesarcipher/dialog/ConsoleText.java
> +    public static final String HELLO_TEXT =
за это лайк!

2022-03-15 21:26 UTC, Enotik-code commented on src/com/javarush/caesarcipher/cipher/CaesarCipher.java
> +public class CaesarCipher {
я бы сделал класс синглом, убрал бы использование стат методов и создал бы просто экземпляр в класс UserDialog

2022-03-15 21:39 UTC, Enotik-code commented on src/com/javarush/caesarcipher/cipher/CaesarCipher.java
> +public class CaesarCipher {
синглтон

2022-03-16 07:35 UTC, neighborstan commented on src/com/javarush/caesarcipher/cipher/CaesarCipher.java
> +        String decryptedText = Files.readString(pathToDecryptedFile);
Имеешь ввиду создать свой класс исключения?

2022-03-16 12:03 UTC, neighborstan commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +            if (action.equals(ENCRYPT)) {
Везде поправил

2022-03-16 12:04 UTC, neighborstan commented on src/com/javarush/caesarcipher/cipher/CaesarCipher.java
> +                    }
Исправил

2022-03-16 12:04 UTC, neighborstan commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +                };
Исправил

2022-03-16 14:47 UTC, neighborstan commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +    }
сделал через один метод

2022-03-16 14:47 UTC, neighborstan commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +            if (action.equals(ENCRYPT)) {
поправил

2022-03-16 14:48 UTC, neighborstan commented on src/com/javarush/caesarcipher/cipher/CaesarCipher.java
> +        Files.writeString(pathToEncryptedFile, builderResultText.toString());
вынес обработку файлов в отдельный класс FileProcessing

2022-03-16 14:48 UTC, neighborstan commented on src/com/javarush/caesarcipher/cipher/CaesarCipher.java
> +                    }
упростил

2022-03-16 14:49 UTC, neighborstan commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +                };
избавился от исключенй

2022-03-16 14:50 UTC, neighborstan commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +                if (key < 1 || key >= alphabetSize) throw new NumberFormatException();
избавился от исключений

2022-03-16 14:51 UTC, neighborstan commented on src/com/javarush/caesarcipher/cipher/CaesarCipher.java
> +public class CaesarCipher {
убрал стат методы, преобразовал класс в синглтон

2022-03-17 21:25 UTC, AndryLat requested changes

2022-03-17 21:25 UTC, AndryLat commented on src/com/javarush/caesarcipher/cipher/CaesarCipher.java
> +            = Arrays.asList(
Не надо так переносить:)

2022-03-17 21:25 UTC, AndryLat commented on src/com/javarush/caesarcipher/cipher/CaesarCipher.java
> +            instance = new CaesarCipher();
можно перенести в конструктор:)

2022-03-17 21:25 UTC, AndryLat commented on src/com/javarush/caesarcipher/cipher/CaesarCipher.java
> +    public void encrypt(Path pathToDecryptedFile, Path pathToEncryptedFile, int cipherKey) {
pathToDecryptedFile можно просто назвать inputFilePath

2022-03-17 21:25 UTC, AndryLat commented on src/com/javarush/caesarcipher/cipher/CaesarCipher.java
> +                builderResultText.append(symbol);
Форматирование странное, почему шаг вперед?

2022-03-17 21:25 UTC, AndryLat commented on src/com/javarush/caesarcipher/cipher/CaesarCipher.java
> +            String encryptedText = FileProcessing.readString(pathToEncryptedFile);
Почему веськод ниже на шаг вперед ушел?

2022-03-17 21:25 UTC, AndryLat commented on src/com/javarush/caesarcipher/cipher/CaesarCipher.java
> +                ) {
почему эти скобки на новой строке?

2022-03-17 21:25 UTC, AndryLat commented on src/com/javarush/caesarcipher/cipher/CaesarCipher.java
> +                String resultString = builderResultText.toString();
зачем указывать в имени переменной ее тип? просто result будет понятно и ясно

2022-03-17 21:25 UTC, AndryLat commented on src/com/javarush/caesarcipher/cipher/CaesarCipher.java
> +                    if (resultString.contains(keyword)) keywordHitsCount++;
не надо такое в одну строку писать. И вообще мы не раз акцентировали внимание, что всегда у ифа пишем фигурные скобки! а еще это можжно в отдельный метод.

2022-03-17 21:25 UTC, AndryLat commented on src/com/javarush/caesarcipher/cipher/CaesarCipher.java
> +    public void bruteForce(Path pathToEncryptedFile, Path pathToDecryptedFile, int bruteForceKey) {
метод большой и непонятный. Лучше хотя бы на три метода еще разбить.

2022-03-17 21:25 UTC, AndryLat commented on src/com/javarush/caesarcipher/cipher/FileProcessing.java
> +            e.printStackTrace();
Прекрасно. Я столько раз акцентировал на этом внимание! Ты "обработал" ошибку И ВЕРНУЛ ПУСТУЮ СТРОКУ! Хоть не null, это радует, но в какой момент я пойму, что что-т ос файлом нет так?на продакшене я это могу узнать через пару дней, когда пару сотен тысяч долларов я потерял, потому что пользователю вместо ошибки вернули пустую строку!

2022-03-17 21:25 UTC, AndryLat commented on src/com/javarush/caesarcipher/dialog/ConsoleText.java
> +            UserDialog.ENCRYPT + " - зашифровать файл\n" +
Вот если бы тебе скинули только эту строку, ты бы понял что хранит в себе UserDialog.ENCRYPT ?

2022-03-17 21:25 UTC, AndryLat commented on src/com/javarush/caesarcipher/dialog/ConsoleText.java
> +    public static final String ENTER_CIPHER_KEY = "Введите ключ шифрования, от 1 до " + (UserDialog.alphabetSize - 1) + " включительно...";
Используй format специфиактор, тут должны быть шаблоны. Также такой код не должен быть заязан на другие классы. Иначе у тебя этот класс завязан на диалоге, а диалог - на этом классе. Цикл. так не должно быть в хорошей архитектуре классов.

2022-03-17 21:25 UTC, AndryLat commented on src/com/javarush/caesarcipher/dialog/ConsoleText.java
> +    public static final String BRUTE_FORCE_KEYS_LIST = "S - небольшой текст\nM - средний текст\nXL - большой текст";
А если завтра ключи поменяются? ой как больно тебе будет бегать по всему коду и искать где эти ключи применяю.тся.

2022-03-17 21:25 UTC, AndryLat commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +    public static final String ENCRYPT     = "E";
почему паблик?

2022-03-17 21:25 UTC, AndryLat commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +    public static final String DECRYPT     = "D";
Зачем этот отступ между именем переменной и присваиванием? Красивости не вижу, все кривое. В джава так не делают, оставь это С++

2022-03-17 21:25 UTC, AndryLat commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +    public static final String BRUTE_FORCE = "B";
имя константы не говорит о ее предназначении.

2022-03-17 21:25 UTC, AndryLat commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +    private static final CaesarCipher caesarCipher = CaesarCipher.getInstance();
Интересный момент. Так лучше не делать. Класс становится: а) не тестируемым б) строго завязанным на эту реализацию. Лучше внедрять эту зависимость через конструктор.

2022-03-17 21:25 UTC, AndryLat commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +    private static final CaesarCipher caesarCipher = CaesarCipher.getInstance();
Ну и понятно, что от статики мы должны уйти.

2022-03-17 21:25 UTC, AndryLat commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +    public static final int alphabetSize = caesarCipher.alphabetSize();
это константа, почему она названа как переменная?

2022-03-17 21:25 UTC, AndryLat commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +            } while (!ENCRYPT.equals(action) && !DECRYPT.equals(action) && !BRUTE_FORCE.equals(action));
Лучше это условие вынести в отдельный метод.

2022-03-17 21:25 UTC, AndryLat commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +                System.out.println(CHOISE_OF_ACTION);
ах да, CHOISE_OF_ACTION тоже не говорит что это на самом деле. а это, как минимум, сообщение.

2022-03-17 21:25 UTC, AndryLat commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +            } while (!ENCRYPT.equals(action) && !DECRYPT.equals(action) && !BRUTE_FORCE.equals(action));
а ENCRYPT как минимум команда.

2022-03-17 21:25 UTC, AndryLat commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +                    System.out.println(ENCRYPTION_SELECTED);
нельзя такие свитчи писать. Тут максимум может быть вызов отдельного метода. Иначе через пару лет этот свичт будет занимать 1-10к строк и будет ужасен.

2022-03-17 21:25 UTC, AndryLat commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +        int key;
зачем объявлять их тут? какой в этом смысл? Где используем, там и объявляем кроме случаев, когда надо иметь доступ к переменной вне цикла, а инициализация происходит в цикле.

2022-03-17 21:25 UTC, AndryLat commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +        while (true) {
Я говорил, что while(true) плохая практика.

2022-03-17 21:25 UTC, AndryLat commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +                case SMALL_TEXT -> bruteForceKey  = 2;
Что такое 2, 5, 8 ?

2022-03-17 21:25 UTC, AndryLat commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +                case SMALL_TEXT -> bruteForceKey  = 2;
на каком основании выбраны эти цифры?

2022-03-17 21:25 UTC, AndryLat commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +                case MEDIUM_TEXT -> bruteForceKey = 5;
Вообще эти команды можно засунуть в enum и там хранить и текст, и ключ вместе. Так будет всем удобнее. и на надо бесконечных свитчей.

2022-03-19 18:59 UTC, neighborstan commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +        while (true) {
говорил, помню ) 
но именно в этом случае не знаю как заменить true легкой кровью...получается что код дублируется или совсем не читаемо получается

2022-03-19 19:01 UTC, neighborstan commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +        int key;
место объявления я изменил но true из цикла никак не получается чтоб красиво было, много часов мучался...

2022-03-19 19:03 UTC, neighborstan commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +                case MEDIUM_TEXT -> bruteForceKey = 5;
ох сделал я enum, в методе код заменил, строк стало меньше но мой enum меня смущает почему-то, обязательно нужен фидбек по этому поводу, есть подозрение что перемутил, подскажи как надо

2022-03-19 19:05 UTC, neighborstan commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +                case SMALL_TEXT -> bruteForceKey  = 2;
эти цифры - это количество совпадений ключевых слов тексте.
Чем больше текст тем  число побольше, для надежности подбора

2022-03-19 19:16 UTC, neighborstan commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +                    System.out.println(ENCRYPTION_SELECTED);
Я б с удовольствием приуменьшил до одного метода только не догоню как, там у меня и так методы разные, сократил по-максимуму, дальше не думается совсем...подскажи куда смотреть. В if-else переделал

2022-03-19 19:20 UTC, neighborstan commented on src/com/javarush/caesarcipher/cipher/CaesarCipher.java
> +            String encryptedText = FileProcessing.readString(pathToEncryptedFile);
поправил

2022-03-19 19:20 UTC, neighborstan commented on src/com/javarush/caesarcipher/cipher/CaesarCipher.java
> +                builderResultText.append(symbol);
поправил

2022-03-19 19:20 UTC, neighborstan commented on src/com/javarush/caesarcipher/cipher/CaesarCipher.java
> +    public void encrypt(Path pathToDecryptedFile, Path pathToEncryptedFile, int cipherKey) {
изменил на input... и output...

2022-03-19 19:21 UTC, neighborstan commented on src/com/javarush/caesarcipher/cipher/CaesarCipher.java
> +            instance = new CaesarCipher();
вот тут тоже не понял совсем, что и зачем перенести?

2022-03-19 19:21 UTC, neighborstan commented on src/com/javarush/caesarcipher/cipher/CaesarCipher.java
> +            = Arrays.asList(
исправил

2022-03-19 19:21 UTC, neighborstan commented on src/com/javarush/caesarcipher/cipher/CaesarCipher.java
> +                ) {
исправил

2022-03-19 19:22 UTC, neighborstan commented on src/com/javarush/caesarcipher/cipher/CaesarCipher.java
> +                String resultString = builderResultText.toString();
изменил

2022-03-19 19:22 UTC, neighborstan commented on src/com/javarush/caesarcipher/cipher/CaesarCipher.java
> +                    if (resultString.contains(keyword)) keywordHitsCount++;
сделано! в отдельный метод вынес

2022-03-19 19:23 UTC, neighborstan commented on src/com/javarush/caesarcipher/cipher/CaesarCipher.java
> +    public void bruteForce(Path pathToEncryptedFile, Path pathToDecryptedFile, int bruteForceKey) {
разбил как мог, сделал 3 метода, больше упросить никак не могу, не вижу )

2022-03-19 19:24 UTC, neighborstan commented on src/com/javarush/caesarcipher/cipher/FileProcessing.java
> +            e.printStackTrace();
этот момент тоже глянь, может я не совсем понял....я вывел сообщения об ошибке, как иначе в этом случае надо поступать не соображу?

2022-03-19 19:24 UTC, neighborstan commented on src/com/javarush/caesarcipher/dialog/ConsoleText.java
> +            UserDialog.ENCRYPT + " - зашифровать файл\n" +
имена изменил

2022-03-19 19:25 UTC, neighborstan commented on src/com/javarush/caesarcipher/dialog/ConsoleText.java
> +    public static final String ENTER_CIPHER_KEY = "Введите ключ шифрования, от 1 до " + (UserDialog.alphabetSize - 1) + " включительно...";
сделал. убрал зависимость от другого класса

2022-03-19 19:26 UTC, neighborstan commented on src/com/javarush/caesarcipher/dialog/ConsoleText.java
> +    public static final String BRUTE_FORCE_KEYS_LIST = "S - небольшой текст\nM - средний текст\nXL - большой текст";
тут я enum сделал, посмотри обязательно, я очень сомневаюсь в своем решении

2022-03-19 19:27 UTC, neighborstan commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +    public static final String ENCRYPT     = "E";
перенес эти константы в метод с шаблонами текстов

2022-03-19 19:27 UTC, neighborstan commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +    public static final String DECRYPT     = "D";
поправил

2022-03-19 19:27 UTC, neighborstan commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +    public static final String BRUTE_FORCE = "B";
изменил имена

2022-03-19 19:30 UTC, neighborstan commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +    private static final CaesarCipher caesarCipher = CaesarCipher.getInstance();
вот тут не понимаю...лучше не делать как ты имеешь ввиду, на что лучше не завязываться?  Синглтон? Не правил этот момент.
Какую зависимость через конструктор тоже не понял?

По синглтону Антон рекомендовал, я сделал обычную реализацию...поясни плиз )

2022-03-19 19:31 UTC, neighborstan commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +    public static final int alphabetSize = caesarCipher.alphabetSize();
поправил

2022-03-19 19:31 UTC, neighborstan commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +            } while (!ENCRYPT.equals(action) && !DECRYPT.equals(action) && !BRUTE_FORCE.equals(action));
сделал

2022-03-19 19:32 UTC, neighborstan commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +                System.out.println(CHOISE_OF_ACTION);
переименовал многие константы

2022-03-22 11:55 UTC, AndryLat commented on src/com/javarush/caesarcipher/cipher/CaesarCipher.java
> +public class CaesarCipher {
Синглтоном не надо злоупотреблять:) Он нужен, когда реально есть надобность только в одном объекте, а тут какая нам разница сколько объектов этого типа создано? так что в целом, лучше не делать синглтоном:) Но можно, исправлять не надо.

2022-03-22 11:55 UTC, AndryLat commented on src/com/javarush/caesarcipher/cipher/FileProcessing.java
> +            e.printStackTrace();
У тебя этот класс должен отвечать за общение с пользователем? НЕТ! Ты должен пробросить ошибку дальше до тех пор, пока она не сможет быть обработана корректно.

2022-03-22 11:55 UTC, AndryLat commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +    private final String BRUTE_FORCE_KEYS_LIST = "%s - небольшой текст\n%s - средний текст\n%s - большой текст".formatted(TextSizeKey.SMALL.getStringKey(), TextSizeKey.MEDIUM.getStringKey(), TextSize
Тебя такие длинные строки не смущают?

2022-03-22 11:55 UTC, AndryLat commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +                System.out.println(ENCRYPTION_SELECTED_MESSAGE);
а вынести в отдельный метод можно? чтобы не было методов в 60 строк. Читать же нереально.

2022-03-24 09:22 UTC, neighborstan commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +    public static final String ENCRYPT     = "E";
вынес их в Enum

2022-03-24 09:23 UTC, neighborstan commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +                    System.out.println(ENCRYPTION_SELECTED);
...и немного сократил еще

2022-03-24 09:24 UTC, neighborstan commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +                case SMALL_TEXT -> bruteForceKey  = 2;
вынес эти ключи и названия в  Enum чтобы в одном месте было и понятней

2022-03-24 09:26 UTC, neighborstan commented on src/com/javarush/caesarcipher/cipher/CaesarCipher.java
> +    public int alphabetSize() {
public потому что используется в другом классе
передвинул выше приватных

2022-03-24 09:26 UTC, neighborstan commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +    private final String BRUTE_FORCE_KEYS_LIST = "%s - небольшой текст\n%s - средний текст\n%s - большой текст".formatted(TextSizeKey.SMALL.getStringKey(), TextSizeKey.MEDIUM.getStringKey(), TextSize
отформатировал )

2022-03-24 09:28 UTC, neighborstan commented on src/com/javarush/caesarcipher/dialog/UserDialog.java
> +                System.out.println(ENCRYPTION_SELECTED_MESSAGE);
максимально подсократил строки, как мог...что можно вынести в отдельный метод не доходит, пытался честно разобраться оч долго

2023-05-06 13:14 UTC, merged